apiVersion: "1.0.0"

app:
  name: "musicsnap"
  env: "dev"
#  env: "prod"
  version: "1.0"

postgres:
  host: "localhost"
  port: "5436"
#  данные заполняются в env файле
  user: "stub_env"
  password: "stub_env"
  ssl: "stub_env"
  name: "stub_env"


logger:
  env: "dev"
#  env: "prod"
  level: "debug"
  outputs:
    - "stdout"
  error_outputs:
    - "stderr"
  encoding: "json"
  sentry_dsn: ""
  sentry_level: "error"

cache_refresher:
  iteration_interval: "10s"

postpone_deleter:
  iteration_interval: "10s"

cache:
  expiration: "900s"
  initial_size: 10000

tracer:
#  enable: false
  enable: true
  exp_target: "localhost:4317"
#  exp_target: "jaeger-all-in-one:4317"
  stdout: false
  trace_file: ".log/traces.json"

metrics:
  enable: false
  dsn: "<sentry_dsn_for_service>"

graceful_shutdown:
  delay: "1s"
  wait_timeout: "10s"
  callback_timeout: "1s"

http:
  host: "localhost"
  port: 8080
  read_timeout: "1s"
  write_timeout: "1s"

kafka_reader:
  brokers:
    - "kafka:9092"
  topic: "outbound"
  id_group: "musicsnap-service"
  min_bytes: 32
  max_bytes: 2048

kafka_writer:
  broker: "kafka:9092"
  topic: "inbound"

jwtservice:
  ttl_hours: 720
#  данные заполняются в env файле
  signingkey: "stub_public_key"
